### ISSUE TITLE
OverlayContainerPosition center?

### ISSUE THREAD

**Issue by klaszlo8207** [MustansirZia/overlay_container#2]
How to center horizontally the box?

**Comment by MustansirZia** [comment]
Hi, @klaszlo8207.
I'm assuming you want to horizontally center it with respect to the widget that's above?

Well, in that case, it depends on how wide the box is with respect to the widget is used alongside with. If the overlay box is larger than the widget above it you might need to give a minus `left` value to the `OverlayContainerPosition`. (Since it would start from where the widget above it does and setting a negative `left` value would move it to the left)
If it is, however, smaller you might want to give a positive `left` value and that will translate it to the right and center it horizontally with respect to the widget above.
